# Generated by Django 3.1 on 2020-08-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.FloatField()),
                ('X1_transaction_date', models.FloatField()),
                ('X2_house_age', models.FloatField()),
                ('X3_distance_to_nearest_MRT_station', models.FloatField()),
                ('X4_number_of_convenience_stores', models.IntegerField()),
                ('X5_latitude', models.FloatField()),
                ('X6_longitude', models.FloatField()),
                ('Y_house_price_of_unit_area', models.FloatField()),
            ],
        ),
    ]
