# Generated by Django 3.1 on 2020-08-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='X3_distance_to_nearest_MRT_station',
        ),
        migrations.AlterField(
            model_name='predresults',
            name='No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X1_transaction_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X2_house_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X5_latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X6_longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='Y_house_price_of_unit_area',
            field=models.IntegerField(),
        ),
    ]
