# Generated by Django 3.1 on 2020-08-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_predresults_prediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='prediction',
            new_name='predictions',
        ),
    ]
