# Generated by Django 3.1 on 2020-08-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20200816_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='predictions',
            field=models.IntegerField(),
        ),
    ]
