# Generated by Django 3.1 on 2020-08-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_remove_predresults_y_house_price_of_unit_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='Y_house_price_of_unit_area',
            field=models.IntegerField(default=True),
        ),
    ]
