# Generated by Django 3.1 on 2020-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_predresults_y_house_price_of_unit_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='X3_distance_to_nearest_MRT_station',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='No',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X1_transaction_date',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X2_house_age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X4_number_of_convenience_stores',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X5_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X6_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='Y_house_price_of_unit_area',
            field=models.FloatField(default=True),
        ),
    ]
