# Generated by Django 3.1 on 2020-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_auto_20200816_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='predictions',
            field=models.CharField(max_length=30),
        ),
    ]
