# Generated by Django 3.1 on 2020-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_auto_20200817_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='No',
            new_name='X1',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X1_transaction_date',
            new_name='X2',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X3_distance_to_nearest_MRT_station',
            new_name='X3',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X2_house_age',
            new_name='X4',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X4_number_of_convenience_stores',
            new_name='X5',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X5_latitude',
            new_name='X6',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X6_longitude',
            new_name='X7',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='Y_house_price_of_unit_area',
            new_name='Y',
        ),
        migrations.AddField(
            model_name='predresults',
            name='X8',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='predresults',
            name='Y1',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='predresults',
            name='Y2',
            field=models.FloatField(default=False),
        ),
    ]
