# Generated by Django 3.1 on 2020-08-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_auto_20200818_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='X1',
            new_name='No',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X2',
            new_name='X1_transaction_date',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X4',
            new_name='X2_house_age',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X3',
            new_name='X3_distance_to_nearest_MRT_station',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X5',
            new_name='X4_number_of_convenience_stores',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X6',
            new_name='X5_latitude',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='X7',
            new_name='X6_longitude',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='Y',
            new_name='Y_house_price_of_unit_area',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='X8',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='Y1',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='Y2',
        ),
    ]
