# Generated by Django 3.1 on 2020-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_auto_20200818_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='No',
            field=models.FloatField(null=True),
        ),
    ]
