# Generated by Django 3.1 on 2020-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_auto_20200818_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='X1_transaction_date',
            field=models.FloatField(null=True),
        ),
    ]
