# Generated by Django 3.1 on 2020-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_auto_20200818_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='X2_house_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X3_distance_to_nearest_MRT_station',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X4_number_of_convenience_stores',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X5_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X6_longitude',
            field=models.FloatField(null=True),
        ),
    ]
