# Generated by Django 3.1 on 2020-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0014_auto_20200818_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='No',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X1_transaction_date',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X2_house_age',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X3_distance_to_nearest_MRT_station',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X4_number_of_convenience_stores',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X5_latitude',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='X6_longitude',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='Y_house_price_of_unit_area',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
