# Generated by Django 3.1 on 2020-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0016_auto_20200818_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='No',
            field=models.FloatField(default=True, null=True),
        ),
    ]
